name: 'Tweet PRs'
description: 'A GitHub Action that will tweet out about the PR when it get's merged as a pat on the back!'
inputs:
  tweet:  # id of input
    description: 'Content of the tweet you wanna make'
    required: true
    default: 'World World'
output: 
  tweet-sent:
    description: 'The tweet that got sent out'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: at-sign
  color: blue