name: Sample worflow on push

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Tweet Activity
      uses: jai-dewani/Tweet-PRs@v0.1.1-alpha
      with:
        tweet: 'This is a test run, change ${github.context.payload.after}'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
