name: Sample worflow on push

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Tweet Activity
      uses: jai-dewani/Tweet-PRs@v0.2.4
      with:
        tweet: 'This is a test run, change ${twitter_username}'
