name: Simple workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Tweet Activity
      uses: jai-dewani/Tweet-PRs@main
      with:
        tweet: 'This is a test run'
        GITHUB_TOKEN: ${{ github.token }}
        TWITTER_API_KEY: ${{ secret.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secret.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secret.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secret.TWITTER_ACCESS_TOKEN_SECRET }}
